In [109]:
# Import Libraries
import pandas as pd
import numpy as np

In [110]:
# Read Long format DF
long_format_df=pd.read_csv('./data/csv/long_format_df.csv')

In [111]:
long_format_df.head()

  users                                  book  rating  user_id  book_id
0   Ben  The Hitchhiker's Guide To The Galaxy       5        1        1
1   Ben                        Watership Down       0        1        2
2   Ben    The Five People You Meet in Heaven       0        1        3
3   Ben                                 Speak       0        1        4
4   Ben       I Know Why the Caged Bird Sings       0        1        5

In [112]:
from scipy.sparse import csr_matrix
long_format_df = long_format_df.drop_duplicates(['users', 'book'])

In [113]:
book_user_pivot = long_format_df.pivot(index = 'book', columns = 'users', values = 'rating').fillna(0)

In [114]:
book_user_pivot.head()

users,Albus Dumbledore,Alexandra,Anna-Carol,Apollo,Ben,Boxxy,Brian,Brix,Cedric Jones,Claire,...,clipper,crom,dencellia,ender,hidan,joe,ma,matt c,sage32,snoosh
book,,,,,,,,,,,,,,,,,,,,,
A Great and Terrible Beauty,0,0,0,0,0,0,0,0,0,0,...,4,0,0,0,0,0,0,0,0,0
Bleach (graphic novel),0,0,0,0,0,5,0,0,0,0,...,0,0,4,0,5,4,0,0,0,0
Bone Series,0,0,0,0,5,0,0,0,0,0,...,0,0,0,0,0,3,0,0,0,1
Brave New World,0,0,0,5,0,0,5,4,0,2,...,0,0,0,0,0,0,2,0,4,5
Breathless,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [115]:
book_user_rating_matrix = csr_matrix(book_user_pivot.values)

from sklearn.neighbors import NearestNeighbors


model_knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute')
model_knn.fit(book_user_rating_matrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [116]:
# query_index = np.random.choice(long_format_pivot.shape[0])
query_index = 37

print(query_index)

37

In [117]:
distances, indices = model_knn.kneighbors(book_user_pivot.iloc[query_index,:].values.reshape(1, -1), n_neighbors = 6)

In [118]:

book_user_pivot.index[query_index]

'The Great Gatsby'

In [119]:
for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(book_user_pivot.index[query_index]))
    else:
        print('{0}: {1}, with distance of {2}:'.format(i, book_user_pivot.index[indices.flatten()[i]], distances.flatten()[i]))

Recommendations for The Great Gatsby:

1: Lord of the Flies, with distance of 0.38399224378494046:
2: Nineteen Eighty-Four (1984), with distance of 0.4361072104424032:
3: The Hitchhiker's Guide To The Galaxy, with distance of 0.4376443122569249:
4: To Kill a Mockingbird, with distance of 0.4437631823741941:
5: Brave New World, with distance of 0.4605450997106373:

# Find Similar Users

In [120]:
user_book_pivot = long_format_df.pivot(index = 'users', columns = 'book', values = 'rating').fillna(0)

In [121]:
user_book_pivot.head()

book,A Great and Terrible Beauty,Bleach (graphic novel),Bone Series,Brave New World,Breathless,Dealing with Dragons,Dinotopia: A Land Apart from Time,Ender's Game,Eragon,Far North,...,The Princess Bride,The Princess Diaries,The Shadow Club,The Sisterhood of the Travelling Pants,The Summer Tree,The War Of The Worlds,Thirteen Reasons Why,To Kill a Mockingbird,Twilight Series,Watership Down
users,,,,,,,,,,,,,,,,,,,,,
Albus Dumbledore,0,0,0,0,0,0,0,0,0,0,...,0,2,0,3,0,0,0,4,1,0
Alexandra,0,0,0,0,0,0,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0
Anna-Carol,0,0,0,0,0,0,0,0,0,0,...,0,0,0,3,0,0,0,3,5,0
Apollo,0,0,0,5,0,0,0,0,0,0,...,0,3,0,4,0,0,0,4,0,0
Ben,0,0,5,0,0,5,0,5,5,5,...,0,2,5,3,0,5,0,3,1,0

In [122]:
user_book_rating_matrix = csr_matrix(user_book_pivot.values)

from sklearn.neighbors import NearestNeighbors


model_knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute')
model_knn.fit(user_book_rating_matrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [123]:
user_book_pivot[user_book_pivot.index=='Tiffany']

book,A Great and Terrible Beauty,Bleach (graphic novel),Bone Series,Brave New World,Breathless,Dealing with Dragons,Dinotopia: A Land Apart from Time,Ender's Game,Eragon,Far North,...,The Princess Bride,The Princess Diaries,The Shadow Club,The Sisterhood of the Travelling Pants,The Summer Tree,The War Of The Worlds,Thirteen Reasons Why,To Kill a Mockingbird,Twilight Series,Watership Down
users,,,,,,,,,,,,,,,,,,,,,
Tiffany,0,3,2,0,0,0,0,0,3,0,...,4,2,0,2,0,5,0,5,1,0

In [124]:
user_book_pivot[user_book_pivot.index=='Hamza ALi']

book,A Great and Terrible Beauty,Bleach (graphic novel),Bone Series,Brave New World,Breathless,Dealing with Dragons,Dinotopia: A Land Apart from Time,Ender's Game,Eragon,Far North,...,The Princess Bride,The Princess Diaries,The Shadow Club,The Sisterhood of the Travelling Pants,The Summer Tree,The War Of The Worlds,Thirteen Reasons Why,To Kill a Mockingbird,Twilight Series,Watership Down
users,,,,,,,,,,,,,,,,,,,,,
Hamza ALi,0,0,0,0,0,0,4,0,3,0,...,0,3,0,1,0,0,0,2,4,0

In [143]:
def find_similar_users(user_name):
    similar_users=[]
    query_index = get_index(user_name)
    if query_index == -1:
        print('{} User Not Found!!'.format(user_name))
    distances, indices = model_knn.kneighbors(user_book_pivot.iloc[query_index,:].values.reshape(1, -1), n_neighbors = 6)
    for i in range(0, len(distances.flatten())):
        if i == 0:
            print('Similar user for {0}:\n'.format(user_book_pivot.index[query_index]))
        else:
            print('{0}: {1}, with distance of {2}:'.format(i, user_book_pivot.index[indices.flatten()[i]], distances.flatten()[i]))
            if distances.flatten()[i]>0 and distances.flatten()[i]<0.2:
                similar_users.append(user_book_pivot.index[indices.flatten()[i]])
    return similar_users

def get_index(user_name):
    for i in range(0,len(user_book_pivot.index)):
            if user_book_pivot.index[i] == user_name:
                return i
    return -1

In [144]:
find_similar_users('Tiffany')

Similar user for Tiffany:

1: Cust8, with distance of 0.09923690500241:
2: Claire, with distance of 0.2214716600583181:
3: Shannon, with distance of 0.23942617589839665:
4: ROFLOL, with distance of 0.26699459482668453:
5: Megan, with distance of 0.2670292202452581:

['Cust8']

In [145]:
similar_users_df=user_book_pivot.index.map(lambda x: {x:find_similar_users(x)})

Similar user for Albus Dumbledore:

1: Joshua, with distance of 0.008358174089109993:
2: Scream, with distance of 0.29422612627795197:
3: Rudy A, with distance of 0.3269438192125802:
4: Cust4, with distance of 0.3645563486053961:
5: NuNu, with distance of 0.3654365472609288:
Similar user for Alexandra:

1: Alexandra, with distance of 0.0:
2: Ella, with distance of 0.49018112346690734:
3: James, with distance of 0.4950444775217575:
4: Nathan, with distance of 0.5527864045000421:
5: Hamza ALi, with distance of 0.5527864045000421:
Similar user for Anna-Carol:

1: YJAM, with distance of 0.466334176072254:
2: James, with distance of 0.4707101910338485:
3: Cust8, with distance of 0.48330445002445077:
4: Ella, with distance of 0.485149215831827:
5: Hideo, with distance of 0.48601744328240637:
Similar user for Apollo:

1: sage32, with distance of 0.3755674845217022:
2: McLean, with distance of 0.38866667132903787:
3: ParseClaws, with distance of 0.42856995945420095:
4: Joshua, with distance of 0.44655395835871836:
5: Jaluka, with distance of 0.45879707269890924:
Similar user for Ben:

1: Reuven, with distance of 0.24623870634879175:
2: Tiffany, with distance of 0.32498606916595496:
3: matt c, with distance of 0.3649737692514875:
4: Claire, with distance of 0.3661650649492173:
5: Cust8, with distance of 0.36926360808839387:
Similar user for Boxxy:

1: Rudy A, with distance of 0.2614510541240036:
2: chrispeh, with distance of 0.3936609374091675:
3: Rudy Ann, with distance of 0.5196155385847386:
4: Sanity, with distance of 0.5821854891016333:
5: Mark, with distance of 0.5855751365088302:
Similar user for Brian:

1: Brian, with distance of 0.0:
2: Claire, with distance of 0.34518362177846074:
3: Tiffany, with distance of 0.3651632995919436:
4: Megan, with distance of 0.3765795958183369:
5: McLean, with distance of 0.37843135506985504:
Similar user for Brix:

1: ParseClaws, with distance of 0.36798549872484987:
2: Mark, with distance of 0.41178952646060896:
3: Priscilla, with distance of 0.4383221685271329:
4: crom, with distance of 0.4524599254442614:
5: Ocelot, with distance of 0.4807461378296357:
Similar user for Cedric Jones:

1: Cust8, with distance of 0.50729549648124:
2: SubRia, with distance of 0.5102999876643343:
3: Leslie, with distance of 0.5317642912390024:
4: andrew, with distance of 0.5486699687633523:
5: Tiffany, with distance of 0.5528561822019227:
Similar user for Claire:

1: Tiffany, with distance of 0.2214716600583181:
2: James, with distance of 0.24307509494499624:
3: Cust8, with distance of 0.2614896266913185:
4: Megan, with distance of 0.2674709162463048:
5: Reuven, with distance of 0.28704583008424234:
Similar user for Cust1:

1: Francois, with distance of 0.0:
2: Mike, with distance of 0.32852525407302413:
3: andrew, with distance of 0.34952232715178777:
4: Moose, with distance of 0.365703929775539:
5: Mike Williams, with distance of 0.37822463257007766:
Similar user for Cust10:

1: Mike, with distance of 0.2561167711671012:
2: Ocelot, with distance of 0.2662345306846663:
3: andrew, with distance of 0.3002474835805975:
4: ParseClaws, with distance of 0.3762839116150405:
5: Cust1, with distance of 0.3957706947373787:
Similar user for Cust2:

1: Martin, with distance of 0.3178397801119831:
2: Zax, with distance of 0.32824855787277996:
3: clipper, with distance of 0.36432584396322887:
4: Reuven, with distance of 0.38658349806087433:
5: Moose, with distance of 0.3912726383262043:
Similar user for Cust3:

1: Sidney, with distance of 0.29152534177569656:
2: hidan, with distance of 0.36546588311236605:
3: Zachary, with distance of 0.3672944608285693:
4: Dude, with distance of 0.38398269532338547:
5: Iren, with distance of 0.39729777228790886:
Similar user for Cust4:

1: Joshua, with distance of 0.3477575848909956:
2: Scream, with distance of 0.360862509293858:
3: Albus Dumbledore, with distance of 0.3645563486053961:
4: NuNu, with distance of 0.40523675676112825:
5: KeeLed, with distance of 0.44562670899615164:
Similar user for Cust5:

1: Claire, with distance of 0.36589673039658643:
2: Strongbad, with distance of 0.3659248608790263:
3: andrew, with distance of 0.37528767682583397:
4: Reuven, with distance of 0.3761205330950622:
5: Mike, with distance of 0.37612635186203747:
Similar user for Cust6:

1: KeeLed, with distance of 0.30132958138429033:
2: Mike Williams, with distance of 0.3801423226828414:
3: Cust8, with distance of 0.38363478312187216:
4: Claire, with distance of 0.38863324856637127:
5: Tiffany, with distance of 0.40861890532734135:
Similar user for Cust7:

1: Megan, with distance of 0.39654596378792917:
2: Iren, with distance of 0.43208318451012184:
3: Shannon, with distance of 0.4671637486378374:
4: ROFLOL, with distance of 0.47297200352922153:
5: Cust8, with distance of 0.4799124311093288:
Similar user for Cust8:

1: Tiffany, with distance of 0.09923690500241:
2: Shannon, with distance of 0.20046485316706897:
3: KeeLed, with distance of 0.23708903714903629:
4: ROFLOL, with distance of 0.24551316614673158:
5: Claire, with distance of 0.2614896266913185:
Similar user for Cust9:

1: ender, with distance of 0.4096383006775117:
2: Mike, with distance of 0.45497018224120855:
3: Reuven, with distance of 0.46500154714552877:
4: ParseClaws, with distance of 0.47100394156777525:
5: Mark, with distance of 0.4819975306375629:
Similar user for David:

1: I. Ned, with distance of 0.4418474084205246:
2: Strongbad, with distance of 0.4827393998881283:
3: James, with distance of 0.5516774275886377:
4: Cust7, with distance of 0.5617078275657162:
5: McLean, with distance of 0.5645015155783784:
Similar user for Don Wang:

1: Hideo, with distance of 0.20666068452241015:
2: McLean, with distance of 0.27550393137242446:
3: hidan, with distance of 0.34558971326524457:
4: Rudy Ann, with distance of 0.34572173348699:
5: Leslie, with distance of 0.3628653250219338:
Similar user for Douglas Anderson:

1: Brian, with distance of 0.0:
2: Claire, with distance of 0.34518362177846074:
3: Tiffany, with distance of 0.3651632995919436:
4: Megan, with distance of 0.3765795958183369:
5: McLean, with distance of 0.37843135506985504:
Similar user for Dude:

1: Cust3, with distance of 0.38398269532338547:
2: Rudy Ann, with distance of 0.4022374223359385:
3: Don Wang, with distance of 0.40453677780210784:
4: NuNu, with distance of 0.42236761485452545:
5: McLean, with distance of 0.45321554562104716:
Similar user for Ella:

1: KeeLed, with distance of 0.34077522277577055:
2: ROFLOL, with distance of 0.34911357463780324:
3: NuNu, with distance of 0.36495821896868696:
4: Nathan, with distance of 0.37173902954030946:
5: Hamza ALi, with distance of 0.37173902954030946:
Similar user for Francois:

1: Francois, with distance of 0.0:
2: Mike, with distance of 0.32852525407302413:
3: andrew, with distance of 0.34952232715178777:
4: Moose, with distance of 0.365703929775539:
5: Mike Williams, with distance of 0.37822463257007766:
Similar user for Hamza ALi:

1: Nathan, with distance of 0.0:
2: KeeLed, with distance of 0.2464594610450077:
3: Rosanna, with distance of 0.25934392018195884:
4: Shannon, with distance of 0.28587590710209654:
5: ROFLOL, with distance of 0.2956964349484519:
Similar user for Harry Potter:

1: Martin, with distance of 0.41595426335568453:
2: dencellia, with distance of 0.4229168371254751:
3: joe, with distance of 0.45644735120728197:
4: Sidney, with distance of 0.4721550092675587:
5: Sanity, with distance of 0.4732921779006869:
Similar user for Hideo:

1: Don Wang, with distance of 0.20666068452241015:
2: snoosh, with distance of 0.24737224171958294:
3: hidan, with distance of 0.2888448325416497:
4: Iren, with distance of 0.30050636304726686:
5: YJAM, with distance of 0.306747759020528:
Similar user for Huxil:

1: YJAM, with distance of 0.45839743969093594:
2: Cust7, with distance of 0.5049262285116629:
3: Cust2, with distance of 0.525228304060461:
4: ender, with distance of 0.5276322268281703:
5: Megan, with distance of 0.5285954792089683:
Similar user for I. Ned:

1: sage32, with distance of 0.38746553628195224:
2: Mike Williams, with distance of 0.39234449760765555:
3: Claire, with distance of 0.4057642373151116:
4: Cust8, with distance of 0.41730972403018773:
5: SubRia, with distance of 0.41808562603735366:
Similar user for Iren:

1: hidan, with distance of 0.2212309632413647:
2: YJAM, with distance of 0.25101204017151346:
3: Zachary, with distance of 0.27490229007164635:
4: Hideo, with distance of 0.30050636304726686:
5: Shannon, with distance of 0.31222767303914867:
Similar user for J-Rok:

1: Strongbad, with distance of 0.5697347270250537:
2: Pablo Sanchez, with distance of 0.5811460917083044:
3: Francois, with distance of 0.5839241388195497:
4: Cust1, with distance of 0.5839241388195497:
5: Cust2, with distance of 0.593421443692637:
Similar user for Jaluka:

1: Sam, with distance of 0.4502077816975162:
2: Apollo, with distance of 0.45879707269890924:
3: ParseClaws, with distance of 0.5168625964975078:
4: McLean, with distance of 0.5445715320187403:
5: chrispeh, with distance of 0.549622650888955:
Similar user for James:

1: Claire, with distance of 0.24307509494499624:
2: Strongbad, with distance of 0.2587073712312036:
3: Tiffany, with distance of 0.3019868722046877:
4: Cust8, with distance of 0.3087480751231453:
5: Reuven, with distance of 0.32608870151912195:
Similar user for Jeremy:

1: Alexandra, with distance of 0.0:
2: Ella, with distance of 0.49018112346690734:
3: James, with distance of 0.4950444775217575:
4: Nathan, with distance of 0.5527864045000421:
5: Hamza ALi, with distance of 0.5527864045000421:
Similar user for Jim C:

1: Priscilla, with distance of 0.36110423827629856:
2: andrew, with distance of 0.3885314355506617:
3: clipper, with distance of 0.39322012378308213:
4: Mike, with distance of 0.39924136194650905:
5: Cust1, with distance of 0.42411056015969273:
Similar user for Joshua:

1: Albus Dumbledore, with distance of 0.008358174089109993:
2: Scream, with distance of 0.30706513281641656:
3: Cust4, with distance of 0.3477575848909956:
4: Rudy A, with distance of 0.3584970974142252:
5: Rudy Ann, with distance of 0.37945728585917626:
Similar user for KeeLed:

1: Cust8, with distance of 0.23708903714903629:
2: Nathan, with distance of 0.2464594610450077:
3: Hamza ALi, with distance of 0.2464594610450077:
4: Tiffany, with distance of 0.29775029198313985:
5: Cust6, with distance of 0.30132958138429033:
Similar user for Leah:

1: Zachary, with distance of 0.395292102093048:
2: Iren, with distance of 0.5062580688989813:
3: dencellia, with distance of 0.5523976920446494:
4: hidan, with distance of 0.5633519969137363:
5: Sidney, with distance of 0.6235294117647059:
Similar user for Leslie:

1: Hideo, with distance of 0.33520497373249536:
2: Don Wang, with distance of 0.3628653250219338:
3: Megan, with distance of 0.36341174524402164:
4: matt c, with distance of 0.37554288619922815:
5: SubRia, with distance of 0.37561387473584107:
Similar user for Mark:

1: ParseClaws, with distance of 0.3213873751090124:
2: joe, with distance of 0.38019601249178314:
3: Ocelot, with distance of 0.4114874572634971:
4: Brix, with distance of 0.41178952646060896:
5: Megan, with distance of 0.4595778336891705:
Similar user for Martin:

1: Moose, with distance of 0.25386661396107946:
2: Cust2, with distance of 0.3178397801119831:
3: andrew, with distance of 0.37588241812535284:
4: Harry Potter, with distance of 0.41595426335568453:
5: Megan, with distance of 0.41644110983031:
Similar user for McLean:

1: Don Wang, with distance of 0.27550393137242446:
2: Douglas Anderson, with distance of 0.37843135506985504:
3: Brian, with distance of 0.37843135506985504:
4: Apollo, with distance of 0.38866667132903787:
5: Claire, with distance of 0.40334374017937946:
Similar user for McLovin:

1: ma, with distance of 0.3318639658914335:
2: SubRia, with distance of 0.36984660928669677:
3: Sanity, with distance of 0.38367544418796595:
4: Hamza ALi, with distance of 0.4465299340307096:
5: Nathan, with distance of 0.4465299340307096:
Similar user for Megan:

1: ROFLOL, with distance of 0.1882825293157152:
2: Shannon, with distance of 0.19592247416740294:
3: Tiffany, with distance of 0.2670292202452581:
4: Claire, with distance of 0.2674709162463048:
5: Cust8, with distance of 0.29051808403675683:
Similar user for Mike:

1: andrew, with distance of 0.1648395226526953:
2: Cust10, with distance of 0.2561167711671012:
3: Ocelot, with distance of 0.2902668470119458:
4: Francois, with distance of 0.32852525407302413:
5: Cust1, with distance of 0.32852525407302413:
Similar user for Mike Williams:

1: Reuven, with distance of 0.3067433701413438:
2: ROFLOL, with distance of 0.32265591177717123:
3: Nathan, with distance of 0.3409483855790094:
4: Hamza ALi, with distance of 0.3409483855790094:
5: Claire, with distance of 0.34815135173624434:
Similar user for Moose:

1: Martin, with distance of 0.25386661396107946:
2: andrew, with distance of 0.2679090979500519:
3: Ocelot, with distance of 0.305365261188263:
4: Megan, with distance of 0.31715613321222924:
5: joe, with distance of 0.34203431079763813:
Similar user for NaRwHaLs:

1: Hideo, with distance of 0.3811808660760031:
2: ROFLOL, with distance of 0.38170039356972096:
3: hidan, with distance of 0.3881623296626928:
4: Iren, with distance of 0.39063228756060553:
5: Megan, with distance of 0.3968280405713428:
Similar user for Nathan:

1: Nathan, with distance of 0.0:
2: KeeLed, with distance of 0.2464594610450077:
3: Rosanna, with distance of 0.25934392018195884:
4: Shannon, with distance of 0.28587590710209654:
5: ROFLOL, with distance of 0.2956964349484519:
Similar user for NuNu:

1: Hamza ALi, with distance of 0.3382758974627055:
2: Nathan, with distance of 0.3382758974627055:
3: KeeLed, with distance of 0.34004067179571273:
4: Ella, with distance of 0.36495821896868696:
5: Albus Dumbledore, with distance of 0.3654365472609288:
Similar user for Ocelot:

1: andrew, with distance of 0.2470822508588203:
2: Cust10, with distance of 0.2662345306846663:
3: Mike, with distance of 0.2902668470119458:
4: joe, with distance of 0.29757110126924635:
5: Moose, with distance of 0.305365261188263:
Similar user for Pablo Sanchez:

1: Don Wang, with distance of 0.4149194818951747:
2: hidan, with distance of 0.5455786788506052:
3: Dude, with distance of 0.5604876568371577:
4: J-Rok, with distance of 0.5811460917083044:
5: Ben, with distance of 0.5853280721056087:
Similar user for ParseClaws:

1: Mark, with distance of 0.3213873751090124:
2: Ocelot, with distance of 0.333284606822989:
3: Brix, with distance of 0.36798549872484987:
4: Cust10, with distance of 0.3762839116150405:
5: andrew, with distance of 0.3936766974014895:
Similar user for Priscilla:

1: Mike, with distance of 0.35563134132935514:
2: Jim C, with distance of 0.36110423827629856:
3: andrew, with distance of 0.38034106528590994:
4: Moose, with distance of 0.3878627284155779:
5: Ocelot, with distance of 0.39238878481716444:
Similar user for ROFLOL:

1: Shannon, with distance of 0.10835240665495816:
2: Megan, with distance of 0.1882825293157152:
3: Cust8, with distance of 0.24551316614673158:
4: Tiffany, with distance of 0.26699459482668453:
5: Nathan, with distance of 0.2956964349484519:
Similar user for Reuven:

1: Ben, with distance of 0.24623870634879175:
2: Claire, with distance of 0.28704583008424234:
3: Mike Williams, with distance of 0.3067433701413438:
4: andrew, with distance of 0.3122143685573342:
5: Ocelot, with distance of 0.32540822523351587:
Similar user for Rosanna:

1: Nathan, with distance of 0.25934392018195884:
2: Hamza ALi, with distance of 0.25934392018195884:
3: Megan, with distance of 0.3690829171727048:
4: ROFLOL, with distance of 0.38336915186222453:
5: Mike Williams, with distance of 0.4007325405711134:
Similar user for Rudy A:

1: Rudy Ann, with distance of 0.17216264561528438:
2: Boxxy, with distance of 0.2614510541240036:
3: Albus Dumbledore, with distance of 0.3269438192125802:
4: Joshua, with distance of 0.3584970974142252:
5: chrispeh, with distance of 0.43277263767479457:
Similar user for Rudy Ann:

1: Rudy A, with distance of 0.17216264561528438:
2: Don Wang, with distance of 0.34572173348699:
3: Scream, with distance of 0.35837634731806234:
4: Albus Dumbledore, with distance of 0.3745927011623751:
5: Joshua, with distance of 0.37945728585917626:
Similar user for Sam:

1: Jaluka, with distance of 0.4502077816975162:
2: Mark, with distance of 0.5582008650141101:
3: chrispeh, with distance of 0.5722073680535015:
4: matt c, with distance of 0.6016517620456712:
5: McLean, with distance of 0.6678323281608196:
Similar user for Sanity:

1: McLovin, with distance of 0.38367544418796595:
2: ma, with distance of 0.4130492093682635:
3: Sidney, with distance of 0.4210674750950736:
4: Harry Potter, with distance of 0.4732921779006869:
5: Scream, with distance of 0.4747742685611097:
Similar user for Scream:

1: Albus Dumbledore, with distance of 0.29422612627795197:
2: Joshua, with distance of 0.30706513281641656:
3: Rudy Ann, with distance of 0.35837634731806234:
4: Cust4, with distance of 0.360862509293858:
5: Rudy A, with distance of 0.4487540894736235:
Similar user for Shannon:

1: ROFLOL, with distance of 0.10835240665495816:
2: Megan, with distance of 0.19592247416740294:
3: Cust8, with distance of 0.20046485316706897:
4: Tiffany, with distance of 0.23942617589839665:
5: Nathan, with distance of 0.28587590710209654:
Similar user for Sidney:

1: hidan, with distance of 0.244121944237224:
2: snoosh, with distance of 0.24816032867157167:
3: Cust3, with distance of 0.29152534177569656:
4: Iren, with distance of 0.31954893528935224:
5: joe, with distance of 0.33185246328555007:
Similar user for Strongbad:

1: James, with distance of 0.2587073712312036:
2: clipper, with distance of 0.30476144859721477:
3: snoosh, with distance of 0.35479834296834156:
4: Claire, with distance of 0.3559291950540503:
5: Cust5, with distance of 0.3659248608790263:
Similar user for SubRia:

1: ROFLOL, with distance of 0.3040910919194869:
2: Cust8, with distance of 0.3083750932200713:
3: Tiffany, with distance of 0.3224237399806231:
4: Nathan, with distance of 0.34939995136764457:
5: Hamza ALi, with distance of 0.34939995136764457:
Similar user for Tiffany:

1: Cust8, with distance of 0.09923690500241:
2: Claire, with distance of 0.2214716600583181:
3: Shannon, with distance of 0.23942617589839665:
4: ROFLOL, with distance of 0.26699459482668453:
5: Megan, with distance of 0.2670292202452581:
Similar user for Tony:

1: Tiffany, with distance of 0.369306517599864:
2: Moose, with distance of 0.40726595425106626:
3: Cust6, with distance of 0.4245845187437002:
4: Claire, with distance of 0.4480839459679694:
5: Cust8, with distance of 0.4508836175009877:
Similar user for YJAM:

1: Iren, with distance of 0.25101204017151346:
2: Hideo, with distance of 0.306747759020528:
3: Shannon, with distance of 0.37899777134320267:
4: Megan, with distance of 0.39487291024924087:
5: snoosh, with distance of 0.4103316226303374:
Similar user for Zachary:

1: Iren, with distance of 0.27490229007164635:
2: hidan, with distance of 0.3533604177839277:
3: Cust3, with distance of 0.3672944608285693:
4: Leah, with distance of 0.395292102093048:
5: Don Wang, with distance of 0.46576947203698227:
Similar user for Zax:

1: Cust2, with distance of 0.32824855787277996:
2: Hideo, with distance of 0.33741084355092077:
3: Francois, with distance of 0.3823900856773812:
4: Cust1, with distance of 0.3823900856773812:
5: snoosh, with distance of 0.3876076500772545:
Similar user for andrew:

1: Mike, with distance of 0.1648395226526953:
2: Ocelot, with distance of 0.2470822508588203:
3: Moose, with distance of 0.2679090979500519:
4: Cust10, with distance of 0.3002474835805975:
5: Reuven, with distance of 0.3122143685573342:
Similar user for chrispeh:

1: Boxxy, with distance of 0.3936609374091675:
2: Albus Dumbledore, with distance of 0.4316419198443946:

In [146]:
similar_users_df

Index([{'Albus Dumbledore': ['Joshua']},                {'Alexandra': []},
                     {'Anna-Carol': []},                   {'Apollo': []},
                            {'Ben': []},                    {'Boxxy': []},
                          {'Brian': []},                     {'Brix': []},
                   {'Cedric Jones': []},                   {'Claire': []},
                          {'Cust1': []},                   {'Cust10': []},
                          {'Cust2': []},                    {'Cust3': []},
                          {'Cust4': []},                    {'Cust5': []},
                          {'Cust6': []},                    {'Cust7': []},
                 {'Cust8': ['Tiffany']},                    {'Cust9': []},
                          {'David': []},                 {'Don Wang': []},
               {'Douglas Anderson': []},                     {'Dude': []},
                           {'Ella': []},                 {'Francois': []},
                      {'Hamza ALi': []},             {'Harry Potter': []},
                          {'Hideo': []},                    {'Huxil': []},
                         {'I. Ned': []},                     {'Iren': []},
                          {'J-Rok': []},                   {'Jaluka': []},
                          {'James': []},                   {'Jeremy': []},
                          {'Jim C': []}, {'Joshua': ['Albus Dumbledore']},
                         {'KeeLed': []},                     {'Leah': []},
                         {'Leslie': []},                     {'Mark': []},
                         {'Martin': []},                   {'McLean': []},
                        {'McLovin': []}, {'Megan': ['ROFLOL', 'Shannon']},
                   {'Mike': ['andrew']},            {'Mike Williams': []},
                          {'Moose': []},                 {'NaRwHaLs': []},
                         {'Nathan': []},                     {'NuNu': []},
                         {'Ocelot': []},            {'Pablo Sanchez': []},
                     {'ParseClaws': []},                {'Priscilla': []},
       {'ROFLOL': ['Shannon', 'Megan']},                   {'Reuven': []},
                        {'Rosanna': []},         {'Rudy A': ['Rudy Ann']},
               {'Rudy Ann': ['Rudy A']},                      {'Sam': []},
                         {'Sanity': []},                   {'Scream': []},
       {'Shannon': ['ROFLOL', 'Megan']},                   {'Sidney': []},
                      {'Strongbad': []},                   {'SubRia': []},
                 {'Tiffany': ['Cust8']},                     {'Tony': []},
                           {'YJAM': []},                  {'Zachary': []},
                            {'Zax': []},             {'andrew': ['Mike']},
                       {'chrispeh': []},                  {'clipper': []},
                           {'crom': []},                {'dencellia': []},
                          {'ender': []},                    {'hidan': []},
                            {'joe': []},                       {'ma': []},
                         {'matt c': []},                   {'sage32': []},
                         {'snoosh': []}],
      dtype='object', name='users')

In [ ]:
#Visualize Results

In [147]:
#Plot the clusters of similarity of users